### ISSUE TITLE
Values in msg.payload are not bound

### ISSUE THREAD

**Issue by consulthys** [noralife/node-red-contrib-cassandra#1]
In `cassandra.html`, the documentation states:

> `msg.payload` can contain an array of values to bind to the topic.

However, in `cassandra.js`, `msg.payload` is not used anywhere and thus the passed values are not bound to the parameters in the query present in `msg.topic`.

**Comment by noralife** [comment]
Hello, thank you for reporting issues and pull requests.
I will take a look tomorrow.
