### ISSUE TITLE
Support batch execution

### ISSUE THREAD

**Issue by consulthys** [noralife/node-red-contrib-cassandra#3]
It would be nice if this node would support [batch execution](https://github.com/datastax/nodejs-driver#batch-multiple-statements) since it's supported by the underlying NodeJS driver.

The idea would be to ensure backward compatibility by still allowing `msg.topic` to be a string (and optionally `msg.payload` to be an array as reported in #1), but also letting `msg.topic` be an array of queries/params. The node would call `execute` or `batch` depending on which case we're in.

**Comment by noralife** [comment]
Thank you for your pull request. Now, this node supports a batch execution.

**Comment by noralife** [comment]
`node-red-contrib-cassandra@0.0.3` includes those changes.
Please update you npm: `npm update node-red-contrib-cassandra`
Thanks

**Comment by muglar** [comment]
Hello,

I see that the node supports batch execution.  Would it be possible to describe how to actually do this?

See attached example.  I am using a template file to write the insert funtion and not bound to the msg.payload (would like to do that do but couldn't figure out the syntax).

Ideally I would sent an array of id,timestamp and value to be batch inserted.

![image](https://cloud.githubusercontent.com/assets/17802517/21412916/bf7fb2c4-c7c1-11e6-9563-398a189bfbe2.png)

**Comment by consulthys** [comment]
Yes, your `msg.topic` field needs to be an array which contains all of your queries.
In the code below, you iterate over `yourRecords` and push one query for each record into the `msg.topic` array. When the Cassandra node [detects that `msg.topic` is an array](https://github.com/noralife/node-red-contrib-cassandra/blob/master/cassandra/cassandra.js#L81), it will trigger batch mode.

```
msg.topic = [];
yourRecords.forEach(function() {
    msg.topic.push({
        query: 'INSERT INTO historian_compact(id, t, v) VALUES (?,?,?)',
        params: [msg.id, msg.date, msg.value]
    });
});

```
